version: '3.8'

services:
  postgres:
    container_name: weather_postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: weather_backend
    build: ./backend/weather-dashboard
    restart: always
    depends_on:
      - postgres
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"

  frontend:
    container_name: weather_frontend
    build: ./frontend/frontend-weather-app
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data: